version: '3.7'
services:
  db:
    image: postgres:12
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "sleep 100000"
    volumes:
      - bundle:/bundle
      - .:/home/app/store
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  bundle:
  postgres: